Algoritmo Ejercicio5
	Escribir "INGRESE LA CANTIDAD DE ZAPATOS QUE DESEA COMPRAR"
	Leer N
	Escribir "INGRESE EL COSTO TOTAL"
	LEER COSTO
	SI N>10 Entonces
		DESCUENTO=COSTO*10/100
		SI N>20 Y N<=30 Entonces
			DESCUENTO=COSTO*20/100
		SiNo
			SI  N>30 ENTONCES
				DESCUENTO=COSTO*40/100
			FinSi
		FinSi
	FinSi
	COSTOTOTAL=COSTO-DESCUENTO
	Escribir "EL DESCUENTO ES:",DESCUENTO
	Escribir "EL COSTO TOTAL ES: ",COSTOTOTAL
FinAlgoritmo
